---

- hosts: all
  become: true
  pre_tasks:
  - name: Update cache
    tags: always
    package:
      update_cache: yes
    changed_when: false

- hosts: all
  become: true
  roles:
  - base

- hosts: web_servers
  become: true
  roles:
  - web_servers

- hosts: db_servers
  become: true
  roles:
  - db_servers
