---

- hosts: all
  become: true
  pre_tasks:
  - name: Update cache
    tags: always
    package:
      update_cache: yes
    changed_when: false

- hosts: web_servers
  become: true
  tasks:
  - name: Install apache and PHP
    tags: apache,apache2,php
    package:
      name:
        - apache2
        - libapache2-mod-php
      state: latest

  - name: Start apache service
    tags: apache,apache2,service
    service:
      name: apache2
      state: started
      enabled: yes

  - name: Copy default site HTML file
    tags: apache,apache2
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:
  - name: Install MySQL
    tags: mysql,db
    package:
     name: mysql-server
     state: latest
