- name: Install Apache and PHP package
  tags: apache,apache2,php
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: Start Apache service
  tags: apache,apache2,service
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: Copy default site HTML file
  tags: apache,apache2
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
